### ISSUE TITLE
route issue

### ISSUE THREAD

**Issue by glamperi** [weimeilin79/financepipeline#8]
I am able to get the blockchain and fisaccount service working.  But, from the gateway, I get this error, is the Host hardcoded somewhere?

java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:286) ~[na:1.8.0_121]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar!/:na]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar!/:na]
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar!/:na]

**Comment by weimeilin79** [comment]
Which host is it trying to ping call? Account or Block chain?

**Comment by glamperi** [comment]
Hi Christina,

  I am using - curl
http://fisgateway-service-fisdemo.apps.172.16.15.210.xip.io/demos/sourcegateway/profile/223455

Here is the logs from the console:

2017-02-21 01:06:50.972 ERROR 1 --- [nio-8080-exec-5]
o.a.camel.processor.DefaultErrorHandler : Failed delivery for (MessageId:
ID-fisgateway-service-2-6umx4-34216-1487636778311-0-40 on ExchangeId:
ID-fisgateway-service-2-6umx4-34216-1487636778311-0-39). Exhausted after
delivery attempt: 1 caught: java.net.NoRouteToHostException: No route to
host (Host unreachable)
Message History
---------------------------------------------------------------------------------------------------------------------------------------

RouteId ProcessorId Processor Elapsed (ms)
[route2 ] [route2 ]
[servlet:/sourcegateway/profile/%7Bacctid%7D?httpMethodRestrict=GET ] [
965]
[route2 ] [restBinding2 ] [ ] [ 0]
[route2 ] [route2 ] [direct:getprofile ] [ 965]
[_getprofileroute ] [_removeHeaders3 ] [removeHeaders[Camel*] ] [ 0]
[_getprofileroute ] [_setHeader3 ] [setHeader[CamelHttpMethod] ] [ 0]
[_getprofileroute ] [_choice3 ] [when[simple{${header.moneysource} ==
'bitcoin'}]choice[] ] [ 966]
[_getprofileroute ] [_recipientList5 ] [recipientList[simple{
http://fisaccount-service:8080/demos/account/profile/${he] [ 966]
Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------

java.net.NoRouteToHostException: No route to host (Host unreachable)

My URL would be ->
http://fisaccount-service-fisdemo.apps.172.16.15.210.xip.io/  not
http://fisaccount-service:8080/demos/account/profile
<http://fisaccount-service:8080/demos/account/profile/$%7Bhe]>

Where do I define this?

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by glamperi** [comment]
Looks like I need to update -> /fisdemoaggregator
<https://github.com/weimeilin79/financepipeline/tree/c536c3a24cc047c0564ef8c09dbabf1bcbe322aa/fisdemoaggregator>
/src
<https://github.com/weimeilin79/financepipeline/tree/c536c3a24cc047c0564ef8c09dbabf1bcbe322aa/fisdemoaggregator/src>
/main
<https://github.com/weimeilin79/financepipeline/tree/c536c3a24cc047c0564ef8c09dbabf1bcbe322aa/fisdemoaggregator/src/main>
/resources
<https://github.com/weimeilin79/financepipeline/tree/c536c3a24cc047c0564ef8c09dbabf1bcbe322aa/fisdemoaggregator/src/main/resources>
/spring
<https://github.com/weimeilin79/financepipeline/tree/c536c3a24cc047c0564ef8c09dbabf1bcbe322aa/fisdemoaggregator/src/main/resources/spring>
/*camel-context.xml*

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by weimeilin79** [comment]
I updated the project couple of days ago, please pull the latest code, it should fix your problem. 
The reason behind it is because if we use binary S2i it'll export service port as 80, and I couldn't get the source S2i maps to 80, for some reason it keeps spinning up 8080 port for the service. So I gave up Source S2i for now. And updated the route to :80 in my gateway camel route.

**Comment by glamperi** [comment]
My names seem different, so I updated the names like this -
http://fisdemoblockchain-fisdemo.apps.172.16.15.210.xip.io
however, you should be able to lookup by the service name, instead of going
to the full url, Rafael/Burr used this in their MSA Helloworld demo, it
should be possible to use this in camel.

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by weimeilin79** [comment]
The problem is with the port, not the service name. And calling external route from the same namespace is not a good practice :)

**Comment by glamperi** [comment]
Agreed, I will try your updates.  Does the pipeline still work with S2I off?

Gary Lamperillo
Principal Solutions Architect
glamperi@redhat.com
(M) 310-896-5282 <callto:310-896-5282>

**Comment by weimeilin79** [comment]
Yep, still does :)
